# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'
platform :ios, ’13.2’
use_frameworks!
target 'NearByApp' do
 pod 'Alamofire','~> 5.0'
 end